# Generated by Django 5.2b1 on 2025-03-31 07:38

import arches.app.models.query_expressions
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "11857_spatial_view_source_identifier_filter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "userpreferenceid",
                    models.UUIDField(
                        db_default=arches.app.models.query_expressions.UUID4(),
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("preferencename", models.CharField(blank=True, max_length=255)),
                ("config", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        models.F("user"),
                        django.db.models.functions.text.Lower("preferencename"),
                        name="unique_preference_name_user",
                    )
                ],
            },
        ),
    ]
